<a href="https://colab.research.google.com/github/yasvanthika122/Deep_Learning/blob/main/Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
print(tf.__version__)

2.15.0


In [ ]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0


11490434/11490434 [==============================] - 0s 0us/step


In [ ]:
#flattern ->standardize & normalize
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [ ]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.06423573, -0.51427335,  0.34098074,  0.19619015,  0.7803675 ,
        -0.3020479 , -0.10943913,  0.27839458,  0.6087402 , -0.09745964]],
      dtype=float32)

In [ ]:
tf.nn.softmax(predictions).numpy()

array([[0.08760963, 0.04912568, 0.11554221, 0.09996751, 0.17929323,
        0.06074029, 0.07364203, 0.10853251, 0.15101744, 0.07452953]],
      dtype=float32)

In [ ]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [ ]:
loss_fn(y_train[:1], predictions).numpy()

2.801148

In [ ]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [ ]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 13s 3ms/step - loss: 0.2989 - accuracy: 0.9128
Epoch 2/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.1427 - accuracy: 0.9584
Epoch 3/5
1875/1875 [==============================] - 5s 2ms/step - loss: 0.1072 - accuracy: 0.9676
Epoch 4/5
1875/1875 [==============================] - 5s 2ms/step - loss: 0.0883 - accuracy: 0.9724
Epoch 5/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0729 - accuracy: 0.9771


In [ ]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - loss: 0.0731 - accuracy: 0.9771 - 972ms/epoch - 3ms/step


[0.0730714425444603, 0.9771000146865845]

In [ ]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [ ]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[7.05147158e-08, 2.96412814e-08, 3.65397045e-06, 1.20583674e-04,
        8.66971859e-12, 1.62025242e-06, 3.77493284e-13, 9.99871254e-01,
        2.65237531e-07, 2.46884451e-06],
       [1.63607385e-08, 1.70673869e-04, 9.99827862e-01, 4.01320051e-07,
        3.73865181e-15, 5.10463849e-07, 5.57660371e-07, 2.75729157e-12,
        6.69297773e-09, 5.88760106e-13],
       [1.82358960e-07, 9.98923242e-01, 2.06710072e-04, 3.12643010e-06,
        1.41397148e-04, 1.99700503e-06, 5.87865907e-05, 5.93097007e-04,
        7.12445399e-05, 2.58568861e-07],
       [9.99691367e-01, 2.18561365e-08, 1.19834076e-04, 7.05962151e-08,
        2.17102098e-07, 1.04109284e-04, 3.88754270e-05, 3.82437829e-05,
        1.04603597e-08, 7.26990220e-06],
       [9.50426147e-06, 2.05433821e-07, 2.42934184e-05, 2.05816221e-07,
        9.97072697e-01, 1.21098637e-07, 7.65210700e-07, 1.39964250e-04,
        1.50742244e-06, 2.75075249e-03]], dtype=float32)>

In [ ]:

from tensorflow.keras.datasets import fashion_mnist

# Load the Fashion MNIST dataset
(train_images, train_labels), (test_images, test_labels) = fashion_mnist.load_data()

# Preprocess the data
train_images = train_images / 255.0
test_images = test_images / 255.0

# Build the model
model = tf.keras.Sequential([
    tf.keras.layers.Flatten(input_shape=(28, 28)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dense(10, activation='softmax')
])

# Compile the model
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

# Train the model
model.fit(train_images, train_labels, epochs=12, batch_size=64, validation_split=0.2)

# Evaluate the model
test_loss, test_acc = model.evaluate(test_images, test_labels)
print(f'Test accuracy: {test_acc * 100:.2f}%')


4422102/4422102 [==============================] - 0s 0us/step
Epoch 1/12
750/750 [==============================] - 3s 4ms/step - loss: 0.5353 - accuracy: 0.8140 - val_loss: 0.4489 - val_accuracy: 0.8454
Epoch 2/12
750/750 [==============================] - 2s 3ms/step - loss: 0.3984 - accuracy: 0.8588 - val_loss: 0.4015 - val_accuracy: 0.8587
Epoch 3/12
750/750 [==============================] - 2s 3ms/step - loss: 0.3596 - accuracy: 0.8702 - val_loss: 0.3576 - val_accuracy: 0.8725
Epoch 4/12
750/750 [==============================] - 3s 4ms/step - loss: 0.3302 - accuracy: 0.8799 - val_loss: 0.3360 - val_accuracy: 0.8798
Epoch 5/12
750/750 [==============================] - 3s 3ms/step - loss: 0.3107 - accuracy: 0.8863 - val_loss: 0.3408 - val_accuracy: 0.8806
Epoch 6/12
750/750 [==============================] - 2s 3ms/step - loss: 0.2943 - accuracy: 0.8924 - val_loss: 0.3373 - val_accuracy: 0.8802
Epoch 7/12
750/750 [==============================] - 2s 3ms/step - loss: 0.2845 - ac

In [ ]:
import tensorflow as tf
from tensorflow.keras.datasets import fashion_mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout
from tensorflow.keras.preprocessing.image import ImageDataGenerator

# Load the Fashion MNIST dataset
(train_images, train_labels), (test_images, test_labels) = fashion_mnist.load_data()

# Reshape and preprocess the data
train_images = train_images.reshape(train_images.shape[0], 28, 28, 1).astype('float32') / 255.0
test_images = test_images.reshape(test_images.shape[0], 28, 28, 1).astype('float32') / 255.0

# Data augmentation
datagen = ImageDataGenerator(
    rotation_range=10,
    width_shift_range=0.1,
    height_shift_range=0.1,
    shear_range=0.1,
    zoom_range=0.1,
    horizontal_flip=True,
    fill_mode='nearest'
)
datagen.fit(train_images)

# Build the CNN model
model = Sequential([
    Conv2D(32, (3, 3), activation='relu', input_shape=(28, 28, 1)),
    MaxPooling2D((2, 2)),
    Conv2D(64, (3, 3), activation='relu'),
    MaxPooling2D((2, 2)),
    Flatten(),
    Dense(128, activation='relu'),
    Dropout(0.5),
    Dense(10, activation='softmax')
])

# Compile the model
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

# Train the model with augmented data
model.fit(datagen.flow(train_images, train_labels, batch_size=64), epochs=20, validation_data=(test_images, test_labels))

# Evaluate the model
test_loss, test_acc = model.evaluate(test_images, test_labels)
print(f'Test accuracy: {test_acc * 100:.2f}%')


Epoch 1/20
938/938 [==============================] - 26s 25ms/step - loss: 0.8372 - accuracy: 0.6904 - val_loss: 0.5349 - val_accuracy: 0.7946
Epoch 2/20
938/938 [==============================] - 22s 23ms/step - loss: 0.6165 - accuracy: 0.7676 - val_loss: 0.4565 - val_accuracy: 0.8339
Epoch 3/20
938/938 [==============================] - 20s 22ms/step - loss: 0.5517 - accuracy: 0.7944 - val_loss: 0.4169 - val_accuracy: 0.8442
Epoch 4/20
938/938 [==============================] - 22s 23ms/step - loss: 0.5160 - accuracy: 0.8083 - val_loss: 0.3839 - val_accuracy: 0.8601
Epoch 5/20
938/938 [==============================] - 22s 23ms/step - loss: 0.4841 - accuracy: 0.8229 - val_loss: 0.3705 - val_accuracy: 0.8637
Epoch 6/20
938/938 [==============================] - 21s 22ms/step - loss: 0.4578 - accuracy: 0.8329 - val_loss: 0.3322 - val_accuracy: 0.8737
Epoch 7/20
938/938 [==============================] - 22s 24ms/step - loss: 0.4492 - accuracy: 0.8335 - val_loss: 0.3375 - val_accuracy: